import type { AppElements } from "./types";

export type UiEventHandlers = {
  onResize: () => void;
  startLeftPanelResize: (event: PointerEvent) => void;
  startRightPanelResize: (event: PointerEvent) => void;
  resetLeftPanelWidth: () => void;
  resetRightPanelWidth: () => void;
  closeMobilePanels: () => void;
  switchProject: () => void;
  renameActiveProject: () => void;
  toggleNewProjectPanel: () => void;
  createProjectFromSelectedTemplate: () => void;
  renderThoughtList: () => void;
  onQuickCaptureSubmit: (event: SubmitEvent) => void;
  toggleMobileCapture: () => void;
  closeMobileCapture: () => void;
  onMobileCaptureSubmit: (event: SubmitEvent) => void;
  handleInboxFilterClick: () => void;
  exportMap: () => void;
  exportMarkdown: () => void;
  importMap: (event: Event) => void;
  toggleSidebar: () => void;
  toggleDetailsPanel: () => void;
  toggleMoreMenu: () => void;
  undoAndCloseMoreMenu: () => void;
  redoAndCloseMoreMenu: () => void;
  fitToGraph: () => void;
  centerAndCloseMoreMenu: () => void;
  openSettingsAndCloseMoreMenu: () => void;
  closeSettings: () => void;
  onColourSchemeChange: () => void;
  onLineThicknessInput: () => void;
  onConnectionTypeChange: () => void;
  onLineEndpointChange: () => void;
  resetViewAndCloseMoreMenu: () => void;
  showMapView: () => void;
  showOutlineView: () => void;
  onTitleInput: () => void;
  showDetailsTab: () => void;
  showNotesTab: () => void;
  showLinksTab: () => void;
  onKindChange: () => void;
  onKindDefaultClick: () => void;
  addKindFromSettings: () => void;
  onNewKindNameKeydown: (event: KeyboardEvent) => void;
  onTagChange: () => void;
  openNoteWorkspace: () => void;
  closeNoteWorkspace: () => void;
  onNoteInput: () => void;
  onNoteBlur: () => void;
  onNotePreviewClick: (event: MouseEvent) => void;
  onNotePreviewKeydown: (event: KeyboardEvent) => void;
  onNoteWorkspaceInput: () => void;
  onNoteWorkspaceKeydown: (event: KeyboardEvent) => void;
  onNoteWorkspacePaste: (event: ClipboardEvent) => void;
  onLinkSubmit: (event: SubmitEvent) => void;
  onConnectedThoughtSubmit: (event: SubmitEvent) => void;
  renderRelationshipPreviews: () => void;
  placeInboxThought: () => void;
  closeInboxReview: () => void;
  previousInboxReviewThought: () => void;
  nextInboxReviewThought: () => void;
  placeInboxReviewAsChild: () => void;
  placeInboxReviewAsParent: () => void;
  placeInboxReviewRelated: () => void;
  keepInboxReviewThought: () => void;
  deleteSelectedThought: () => void;
  onPointerDown: (event: PointerEvent) => void;
  onPointerMove: (event: PointerEvent) => void;
  onPointerUp: (event: PointerEvent) => void;
  clearHoverThought: () => void;
  onGraphContextMenu: (event: MouseEvent) => void;
  onWheel: (event: WheelEvent) => void;
  onNodeCreateSubmit: (event: SubmitEvent) => void;
  closeContextMenu: () => void;
  onLinkEditSubmit: (event: SubmitEvent) => void;
  unlinkContextLink: () => void;
  renderLinkRetargetOptions: () => void;
  retargetContextLink: () => void;
  onDocumentPointerDown: (event: PointerEvent) => void;
  onDocumentPointerMove: (event: PointerEvent) => void;
  onDocumentPointerUp: (event: PointerEvent) => void;
  onKeyDown: (event: KeyboardEvent) => void;
};

export function bindUiEvents(els: AppElements, handlers: UiEventHandlers): void {
  window.addEventListener("resize", handlers.onResize);

  els.leftResizeHandle.addEventListener("pointerdown", handlers.startLeftPanelResize);
  els.rightResizeHandle.addEventListener("pointerdown", handlers.startRightPanelResize);
  els.leftResizeHandle.addEventListener("dblclick", handlers.resetLeftPanelWidth);
  els.rightResizeHandle.addEventListener("dblclick", handlers.resetRightPanelWidth);
  els.libraryCloseButton.addEventListener("click", handlers.closeMobilePanels);
  els.projectSelect.addEventListener("change", handlers.switchProject);
  els.projectNameInput.addEventListener("change", handlers.renameActiveProject);
  els.newProjectToggleButton.addEventListener("click", handlers.toggleNewProjectPanel);
  els.createTemplateButton.addEventListener("click", handlers.createProjectFromSelectedTemplate);
  els.searchInput.addEventListener("input", handlers.renderThoughtList);
  els.quickCaptureForm.addEventListener("submit", handlers.onQuickCaptureSubmit);
  els.mobileCaptureButton.addEventListener("click", handlers.toggleMobileCapture);
  els.mobileCaptureCancelButton.addEventListener("click", handlers.closeMobileCapture);
  els.mobileCaptureForm.addEventListener("submit", handlers.onMobileCaptureSubmit);
  els.tagFilterInput.addEventListener("change", handlers.renderThoughtList);
  els.inboxFilterButton.addEventListener("click", handlers.handleInboxFilterClick);
  els.exportButton.addEventListener("click", handlers.exportMap);
  els.markdownExportButton.addEventListener("click", handlers.exportMarkdown);
  els.importInput.addEventListener("change", handlers.importMap);
  els.sidebarToggleButton.addEventListener("click", handlers.toggleSidebar);
  els.detailsToggleButton.addEventListener("click", handlers.toggleDetailsPanel);
  els.moreButton.addEventListener("click", handlers.toggleMoreMenu);
  els.undoButton.addEventListener("click", handlers.undoAndCloseMoreMenu);
  els.redoButton.addEventListener("click", handlers.redoAndCloseMoreMenu);
  els.fitButton.addEventListener("click", handlers.fitToGraph);
  els.centerButton.addEventListener("click", handlers.centerAndCloseMoreMenu);
  els.settingsButton.addEventListener("click", handlers.openSettingsAndCloseMoreMenu);
  els.settingsMenuButton.addEventListener("click", handlers.openSettingsAndCloseMoreMenu);
  els.settingsCloseButton.addEventListener("click", handlers.closeSettings);
  els.colourSchemeInput.addEventListener("change", handlers.onColourSchemeChange);
  els.lineThicknessInput.addEventListener("input", handlers.onLineThicknessInput);
  els.connectionTypeInput.addEventListener("change", handlers.onConnectionTypeChange);
  els.lineEndpointInput.addEventListener("change", handlers.onLineEndpointChange);
  els.resetButton.addEventListener("click", handlers.resetViewAndCloseMoreMenu);
  els.mapViewButton.addEventListener("click", handlers.showMapView);
  els.outlineViewButton.addEventListener("click", handlers.showOutlineView);
  els.detailsTabDetails.addEventListener("click", handlers.showDetailsTab);
  els.detailsTabNotes.addEventListener("click", handlers.showNotesTab);
  els.detailsTabLinks.addEventListener("click", handlers.showLinksTab);
  els.titleInput.addEventListener("input", handlers.onTitleInput);
  els.kindInput.addEventListener("change", handlers.onKindChange);
  els.kindDefaultButton.addEventListener("click", handlers.onKindDefaultClick);
  els.addKindButton.addEventListener("click", handlers.addKindFromSettings);
  els.newKindNameInput.addEventListener("keydown", handlers.onNewKindNameKeydown);
  els.tagInput.addEventListener("change", handlers.onTagChange);
  els.openNoteWorkspaceButton.addEventListener("click", handlers.openNoteWorkspace);
  els.closeNoteWorkspaceButton.addEventListener("click", handlers.closeNoteWorkspace);
  els.noteInput.addEventListener("input", handlers.onNoteInput);
  els.noteInput.addEventListener("blur", handlers.onNoteBlur);
  els.notePreview.addEventListener("click", handlers.onNotePreviewClick);
  els.notePreview.addEventListener("keydown", handlers.onNotePreviewKeydown);
  els.noteWorkspaceInput.addEventListener("input", handlers.onNoteWorkspaceInput);
  els.noteWorkspaceInput.addEventListener("keydown", handlers.onNoteWorkspaceKeydown);
  els.noteWorkspaceInput.addEventListener("paste", handlers.onNoteWorkspacePaste);
  els.linkForm.addEventListener("submit", handlers.onLinkSubmit);
  els.connectedThoughtForm.addEventListener("submit", handlers.onConnectedThoughtSubmit);
  els.linkTargetInput.addEventListener("input", handlers.renderRelationshipPreviews);
  els.linkTargetInput.addEventListener("change", handlers.renderRelationshipPreviews);
  els.linkRelationInput.addEventListener("change", handlers.renderRelationshipPreviews);
  els.placeTargetInput.addEventListener("change", handlers.renderRelationshipPreviews);
  els.placeRelationInput.addEventListener("change", handlers.renderRelationshipPreviews);
  els.placeThoughtButton.addEventListener("click", handlers.placeInboxThought);
  els.detailsCloseButton.addEventListener("click", handlers.closeMobilePanels);
  els.mobileScrim.addEventListener("click", handlers.closeMobilePanels);
  els.inboxReviewCloseButton.addEventListener("click", handlers.closeInboxReview);
  els.inboxReviewPrevButton.addEventListener("click", handlers.previousInboxReviewThought);
  els.inboxReviewNextButton.addEventListener("click", handlers.nextInboxReviewThought);
  els.inboxReviewTargetInput.addEventListener("change", handlers.renderRelationshipPreviews);
  els.inboxReviewChildButton.addEventListener("click", handlers.placeInboxReviewAsChild);
  els.inboxReviewParentButton.addEventListener("click", handlers.placeInboxReviewAsParent);
  els.inboxReviewRelatedButton.addEventListener("click", handlers.placeInboxReviewRelated);
  els.inboxReviewKeepButton.addEventListener("click", handlers.keepInboxReviewThought);
  els.deleteButton.addEventListener("click", handlers.deleteSelectedThought);
  els.graph.addEventListener("pointerdown", handlers.onPointerDown);
  els.graph.addEventListener("pointermove", handlers.onPointerMove);
  els.graph.addEventListener("pointerup", handlers.onPointerUp);
  els.graph.addEventListener("pointercancel", handlers.onPointerUp);
  els.graph.addEventListener("pointerleave", handlers.clearHoverThought);
  els.graph.addEventListener("contextmenu", handlers.onGraphContextMenu);
  els.graph.addEventListener("wheel", handlers.onWheel, { passive: false });
  els.nodeCreateForm.addEventListener("submit", handlers.onNodeCreateSubmit);
  els.nodeCreateCancelButton.addEventListener("click", handlers.closeContextMenu);
  els.linkEditForm.addEventListener("submit", handlers.onLinkEditSubmit);
  els.linkUnlinkButton.addEventListener("click", handlers.unlinkContextLink);
  els.linkKeepInput.addEventListener("change", handlers.renderLinkRetargetOptions);
  els.linkRetargetButton.addEventListener("click", handlers.retargetContextLink);
  document.addEventListener("pointerdown", handlers.onDocumentPointerDown);
  document.addEventListener("pointermove", handlers.onDocumentPointerMove);
  document.addEventListener("pointerup", handlers.onDocumentPointerUp);
  document.addEventListener("pointercancel", handlers.onDocumentPointerUp);
  window.addEventListener("keydown", handlers.onKeyDown);
}
